# -*- coding: utf-8 -*-
"""Diseases_Detection_FineTuned.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/199t2zK-k2i1JVwJFRLHrynSAZbQgWhN_
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
cattle_diseases_dataset_path = kagglehub.dataset_download('devang03mgr/cattle-diseases-datasets')

print('Data source import complete.')

import os

# List the contents of the downloaded dataset to understand its structure
print(f"Contents of the downloaded dataset at {cattle_diseases_dataset_path}:")
for root, dirs, files in os.walk(cattle_diseases_dataset_path):
    level = root.replace(cattle_diseases_dataset_path, '').count(os.sep)
    indent = ' ' * 4 * (level)
    print(f'{indent}{os.path.basename(root)}/')
    subindent = ' ' * 4 * (level + 1)
    for f in files[:5]: # print only first 5 files in each directory
        print(f'{subindent}{f}')
    if len(files) > 5:
        print(f'{subindent}...(and {len(files) - 5} more files)')

import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, BatchNormalization, Dropout
from keras.applications.vgg16 import VGG16

import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, BatchNormalization, Dropout
from keras.applications.vgg16 import VGG16

# Update Root_dir to point to the new dataset path
Root_dir = os.path.join(cattle_diseases_dataset_path, "Cows datasets")

# Get disease class names from the subdirectories within Root_dir
Diseases_classes = sorted(os.listdir(Root_dir)) # Sort for consistent order

print(f"Dataset Root Directory: {Root_dir}")
print(f"Identified Disease Classes: {Diseases_classes}")

plant_names = []
Len = []
for i in Diseases_classes:
    plant_names.append(i)
    imgs_path = os.listdir(Root_dir + "/" + i)
    Len.append(len(imgs_path))

Len.sort(reverse=True)

sns.set(style="whitegrid", color_codes=True)
plt.figure(figsize=(20,20),dpi=200)
ax = sns.barplot(x= Len, y= plant_names, palette="Greens")
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.show()

from tensorflow import keras

# generators - divides data into batches
image_size = (256, 256)
batch_size = 32
seed = 123 # For reproducible split

train_dataset = keras.utils.image_dataset_from_directory(
    directory=Root_dir,
    labels='inferred',
    label_mode='int',
    batch_size=batch_size,
    image_size=image_size,
    validation_split=0.2, # 20% for validation and test
    subset='training',
    seed=seed
)

validation_dataset = keras.utils.image_dataset_from_directory(
    directory=Root_dir,
    labels='inferred',
    label_mode='int',
    batch_size=batch_size,
    image_size=image_size,
    validation_split=0.2, # 20% for validation and test
    subset='validation',
    seed=seed
)

# For test_dataset, since there's no explicit test folder in this dataset,
# we will create it from the main directory for demonstration purposes,
# similar to how the previous `test_ds` was used. This is not an independent
# test set for model evaluation but for showcasing predictions.
test_dataset = keras.utils.image_dataset_from_directory(
    directory=Root_dir, # Use the full directory for demonstration purposes
    labels='inferred',
    label_mode='int',
    batch_size=batch_size,
    image_size=image_size,
    shuffle=False # Keep order consistent for demonstration
)

# Normalize
def process(image, label):
  image=tf.cast(image/255. , tf.float32)
  return image,label

train_ds=train_dataset.map(process)
validation_ds=validation_dataset.map(process)
test_ds=test_dataset.map(process)

conv_base = keras.applications.Xception(
    weights='imagenet',  # Load weights pre-trained on ImageNet.
    input_shape=(256, 256, 3),
    include_top=False)  # Do not include the ImageNet classifier at the top.

conv_base.trainable = True

set_trainable = False

for layer in conv_base.layers:
  if layer.name == 'block14_sepconv1':
    set_trainable = True
  if set_trainable:
    layer.trainable = True
  else:
    layer.trainable = False

for layer in conv_base.layers:
  print(layer.name,layer.trainable)

conv_base.summary()

model = Sequential()

model.add(conv_base)
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(len(Diseases_classes),activation='softmax'))

# model=Sequential()
# model.add(Conv2D(32,kernel_size=(3,3),padding='valid',activation='relu',input_shape=(256,256,3)))
# model.add(BatchNormalization())
# model.add(MaxPooling2D(pool_size=(2,2),strides=2,padding='valid'))

# model.add(Conv2D(64,kernel_size=(3,3),padding='valid',activation='relu'))
# model.add(BatchNormalization())
# model.add(MaxPooling2D(pool_size=(2,2),strides=2,padding='valid'))

# model.add(Conv2D(128,kernel_size=(3,3),padding='valid',activation='relu'))
# model.add(BatchNormalization())
# model.add(MaxPooling2D(pool_size=(2,2),strides=2,padding='valid'))

# model.add(Flatten())

# model.add(Dense(128,activation='relu'))
# model.add(Dropout(0.1))
# model.add(Dense(64,activation='relu'))
# model.add(Dropout(0.1))
# model.add(Dense(len(Diseases_classes),activation='softmax'))

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

model.summary()

from tensorflow.keras.callbacks import EarlyStopping

# Define EarlyStopping callback
early_stopping = EarlyStopping(
    monitor='val_loss', # Monitor the validation loss
    patience=5,         # Stop if val_loss doesn't improve for 5 epochs
    restore_best_weights=True # Restore model weights from the epoch with the best value of the monitored quantity
)

print("EarlyStopping callback defined.")

history = model.fit(
    train_ds,
    epochs=30, # Keep a higher number of epochs, EarlyStopping will stop it sooner if needed
    validation_data=validation_ds,
    callbacks=[early_stopping] # Add the EarlyStopping callback here
)

history=model.fit(train_ds,epochs=30,validation_data=validation_ds)

import matplotlib.pyplot as plt
plt.plot(history.history['accuracy'],color='red',label='train')
plt.plot(history.history['val_accuracy'],color='blue',label='validation')
plt.legend()
plt.show

model.save('plant_disease_model_1.keras')

from tensorflow import keras

loaded_model = keras.models.load_model('plant_disease_model.keras')
print('Model loaded successfully.')

"""### Image Preprocessing Function
I will create a function `preprocess_image` that performs the requested preprocessing steps:
1.  Resizing the image to 256x256 pixels.
2.  Checking if the image is entirely dark or entirely light.
3.  Checking if the image has a greenish tone. This is a heuristic check to ensure the image might contain plant-related content.

Images that fail these checks will be flagged, and the model prediction will not proceed for them.
"""

import tensorflow as tf
import numpy as np
import json

def preprocess_image(image, target_size=(256, 256)):
    """Preprocesses an image for the model: resizes, checks for darkness/lightness, and greenish tone."""

    # Convert image to TensorFlow tensor if not already
    if not tf.is_tensor(image):
        image = tf.convert_to_tensor(image, dtype=tf.float32)

    # 1. Resize image
    image = tf.image.resize(image, target_size)
    image = image / 255.0  # Normalize pixel values to [0, 1]

    # Convert to numpy for color checks, assuming RGB
    image_np = image.numpy()

    # 2. Check if the image is fully dark or fully light
    mean_pixel_value = np.mean(image_np)
    if mean_pixel_value < 0.1:  # Threshold for 'too dark'
        return None, "Image is too dark to process."
    if mean_pixel_value > 0.9:  # Threshold for 'too light'
        return None, "Image is too light to process."

    # 3. Check for greenish tone (heuristic)
    # A simple check: green channel should be significantly higher than red and blue on average
    # This is a general indicator for plant images. Thresholds can be adjusted.
    red_channel = image_np[:, :, 0]
    green_channel = image_np[:, :, 1]
    blue_channel = image_np[:, :, 2]

    avg_red = np.mean(red_channel)
    avg_green = np.mean(green_channel)
    avg_blue = np.mean(blue_channel)

    # Check if green is dominant
    if not (avg_green > avg_red * 1.1 and avg_green > avg_blue * 1.1):
        return None, "Image does not appear to have a strong greenish tone (may not be a plant image)."

    return image, None

"""### Prediction Function with Confidence Threshold and JSON Output
Next, I will create a function `predict_image_and_format_json` that takes a preprocessed image, makes a prediction using the loaded model, applies a confidence threshold of 0.8, and returns the top 3 predictions in JSON format.

**Note on `test_ds`:** The `test_dataset` was inferred to contain images of only 1 class (`Found 33 files belonging to 1 classes.`). This likely means the test images are in a flat directory without subfolders for individual disease classes. Therefore, the `true_label` provided by `test_ds` will always be `0`, and we cannot accurately display the *actual* true disease label for these test images. We will only show the predicted disease and its confidence.
"""

def predict_image_and_format_json(model, processed_image, class_names, confidence_threshold=0.8, top_n=3):
    """Predicts the class of a preprocessed image and returns top N predictions in JSON format."""

    # Add a batch dimension to the image for model prediction
    img_batch = tf.expand_dims(processed_image, 0)

    predictions = model.predict(img_batch, verbose=0)[0]

    # Get probabilities and sort them
    sorted_indices = np.argsort(predictions)[::-1]

    json_predictions = []
    for i in range(min(top_n, len(class_names))):
        idx = sorted_indices[i]
        confidence = float(predictions[idx]) # Convert to float for JSON compatibility

        if confidence >= confidence_threshold:
            disease_name = class_names[idx]
            json_predictions.append({"class": disease_name, "confidence": confidence})
        else:
            # If the top prediction doesn't meet the threshold, stop.
            # Or, if we want to show anything below threshold, remove this break.
            break

    if not json_predictions:
        return json.dumps([{"message": "No prediction met the confidence threshold."}]), False

    return json.dumps(json_predictions, indent=2), True

"""### Demonstrating Preprocessing and Prediction
Now, let's use these functions on a few images from the `test_ds` to see them in action. We'll display the image, any preprocessing messages, and the JSON output of the top predictions.
"""

import matplotlib.pyplot as plt

# Ensure Diseases_classes is accessible (it was defined earlier)
# If running this cell independently, you might need to re-run the cell where Diseases_classes is defined.

plt.figure(figsize=(20, 20))

num_display_images = 9 # Display up to 9 images

for i, (image_tensor, true_label_tensor) in enumerate(test_ds.unbatch().take(num_display_images)):
    ax = plt.subplot(3, 3, i + 1)

    # Convert tensor to numpy for initial display if needed
    original_image_np = image_tensor.numpy().astype(int) # original image is not normalized
    plt.imshow(original_image_np)
    plt.axis("off")

    # Preprocess the image
    processed_image, preprocessing_message = preprocess_image(image_tensor)

    if preprocessing_message:
        plt.title(f"Preprocessing failed:\n{preprocessing_message}", color='red')
        print(f"Image {i+1}: Preprocessing failed - {preprocessing_message}")
        continue

    # Make predictions with the new function
    json_output, success = predict_image_and_format_json(loaded_model, processed_image, Diseases_classes, confidence_threshold=0.8, top_n=3)

    if success:
        # Parse JSON to display more readably in title
        predictions_data = json.loads(json_output)
        title_str = ""
        for pred in predictions_data:
            title_str += f"{pred['class']}: {pred['confidence']:.2f}\n"
        plt.title(f"Predictions (Top 3 >=0.8):\n{title_str.strip()}")
    else:
        # This branch handles 'No prediction met the confidence threshold.'
        predictions_data = json.loads(json_output)
        plt.title(f"Predictions:\n{predictions_data[0]['message']}", color='orange')

    # Also print the full JSON to the console for easy copy-pasting
    print(f"\n--- Image {i+1} ---\nTrue Label (from test_ds, may be generic): {true_label_tensor.numpy()}\nPredictions: {json_output}")

plt.tight_layout()
plt.show()

# Make predictions on the test data
predictions = loaded_model.predict(test_ds)

# Get predicted class indices
predicted_classes = np.argmax(predictions, axis=1)

print(f"Predictions made for {len(predicted_classes)} test images.")

# Display some sample predictions
plt.figure(figsize=(20, 10))
for i, (image, true_label) in enumerate(test_ds.unbatch().take(9)):
    ax = plt.subplot(3, 3, i + 1)
    plt.imshow(image.numpy())
    predicted_class_index = predicted_classes[i]
    predicted_disease = Diseases_classes[predicted_class_index]
    true_disease = Diseases_classes[true_label.numpy()]
    plt.title(f"True: {true_disease}\nPredicted: {predicted_disease}")
    plt.axis("off")
plt.show()

